on:
    workflow_dispatch:
    push:
        branches:
        - main

permissions:
  id-token: write
  contents: read

env:
  IMAGE_TAG: ${{ github.sha }}
  BACKEND_ECR_REPOSITORY: devops-na-nuvem-week/production/backend
  FRONTEND_ECR_REPOSITORY: devops-na-nuvem-week/production/frontend
jobs:
  backend:
    name: Backend Deployment
    runs-on: ubuntu-latest
    steps:

    - name: Checking code out
      uses: actions/checkout@v4
      
    - name: AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{vars.AWS_REGION}}
        role-to-assume: ${{vars.DEPLOYMENT_ROLE_ARN}}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
          docker build -f ./backend/YoutubeLiveApp/Docker -t $REGISTRY/$BACKEND_ECR_REPOSITORY:$IMAGE_TAG ./backend/YoutubeLiveApp
          docker push $REGISTRY/$BACKEND_ECR_REPOSITORY:$IMAGE_TAG

    - uses: actions/checkout@v4
      with:
        repository: 'kenerry-serain/devops-na-nuvem-week-06-gitops'
        token: ${{ secrets.PAT }}

    - name: Change Image Version
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        kustomize edit set image $REGISTRY/$BACKEND_ECR_REPOSITORY=$REGISTRY/$BACKEND_ECR_REPOSITORY:$IMAGE_TAG
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add ./kustomization.yml
        git commit -m "[Bot] Changing image to $REGISTRY/$BACKEND_ECR_REPOSITORY:$IMAGE_TAG"
        git push